#server:
#  port: 8088
#  session.timeout: 1800
#  tomcat.uri-encoding: UTF-8

#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8
#        username: root
#        password: root
#        driverClassName: com.mysql.jdbc.Driver
#        max-idle: 10
#        max-wait: 10000
#        min-idle: 5
#        initial-size: 5
#    thymeleaf:
#        cache: false
#        cache-period: 0
#        template.cache: false

#    jpa:
#        database: MYSQL
#        hibernate:
#            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#
#        properties:
#            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

#mybatis:
#    mapperLocations: classpath:mappers/*.xml
#    typeAliasesPackage: org.bedoing.entity